version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_HOST: '%'

  redis:
    image: redis:3.2-alpine
    command: redis-server
    ports:
      - '6329:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  app:
    image: amigo_secreto:1.0
    depends_on:
      - db
      - redis
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - gems:/gems
    links:
      - db
      - redis
    env_file:
      - env-prod.env

  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - app
    ports:
      - "80:80"

  jobs:
    depends_on:
      - db
      - redis
      - app
    build: .
    command: bash start_jobs.sh
    volumes:
      - gems:/gems
    env_file:
      - env-prod.env

volumes:
  db:
  redis:
  gems:
